const allSongs = [
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        {title: 'Perfect', firstName: 'Ed', lastName: 'Sheeran', genre: 'Pop', ensemble: ['v', 'vc', 'vp', 'vh']},
        
]

